server:
  port: 8080
  servlet:
    context-path: /tijian

logging:
  level:
    org.springframework: debug
    com.neusoft.tijian.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf-8
    username: root
    password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.tijian.po,com.neusoft.tijian.dto