server:
  port: 8088
  servlet:
    context-path: /tijiancms

logging:
  level:
    org.springframework: debug
    com.neusoft.tijian.mapper: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.tijiancmsserver.po,com.neusoft.tijiancmsserver.dto
